In [1]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('train.csv', usecols=['Age', 'Pclass', 'Fare', 'Survived'])

In [11]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [13]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [20]:
x=df.drop(columns=['Survived'])
y=df['Survived']

x_train,x_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=0
)

In [21]:
x_train.head()

     Pclass   Age     Fare
140       3   NaN  15.2458
439       2  31.0  10.5000
817       2  31.0  37.0042
378       3  20.0   4.0125
491       3  21.0   7.2500

In [29]:
knn=KNNImputer(n_neighbors=3,weights='distance')

x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [30]:
x_train_trf

array([[ 3.        ,  9.00003581, 15.2458    ],
       [ 2.        , 31.        , 10.5       ],
       [ 2.        , 31.        , 37.0042    ],
       ...,
       [ 3.        , 18.5       ,  7.7333    ],
       [ 3.        , 36.        , 17.4       ],
       [ 2.        , 60.        , 39.        ]], shape=(712, 3))

In [31]:
lr=LogisticRegression()

lr.fit(x_train_trf,y_train)
y_predcit=lr.predict(x_test_trf)

accuracy_score(y_test,y_predcit)

0.7318435754189944

In [32]:
# Comparision with Simple Imputer --> mean

In [36]:
si=SimpleImputer()

x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)

In [37]:
lr=LogisticRegression()

lr.fit(x_train_trf2,y_train)
y_predict2=lr.predict(x_test_trf2)

In [38]:
accuracy_score(y_test,y_predict2)

0.7318435754189944