In [1]:
import pandas as pd

# Wroking With Json File

In [2]:
pd.read_json('schedules.json')

,arrival,day,train_name,station_name,station_code,id,train_number,departure
0,None,1.0,Falaknuma Lingampalli MMTS,KACHEGUDA FALAKNUMA,FM,302214,47154,07:55:00
1,None,1.0,Thrissur Guruvayur Passenger,THRISUR,TCR,281458,56044,18:55:00
2,None,1.0,Porbandar Muzaffarpur Express,PORBANDAR,PBR,309335,19269,15:05:00
3,None,1.0,RAIPUR ITWARI PASS,RAIPUR JN,R,283774,58205,13:30:00
4,None,1.0,Gomoh-Asansol MEMU,GOMOH JN,GMO,319937,63542,07:20:00
...,...,...,...,...,...,...,...,...
417075,12:39:00,2.0,HOWRAH - JAYNAGAR Passenger,RAJANAGAR,RJA,424266,53041,12:39:00
417076,12:46:00,2.0,HOWRAH - JAYNAGAR Passenger,LALIT LAKSHMIPR,LLPR,424267,53041,12:47:00
417077,12:59:00,2.0,HOWRAH - JAYNAGAR Passenger,KHAJAULI,KJI,424268,53041,13:00:00
417078,13:09:00,2.0,HOWRAH - JAYNAGAR Passenger,KORAHIA,KRHA,424269,53041,13:10:00
417079,14:20:00,2.0,HOWRAH - JAYNAGAR Passenger,JAYNAGAR,JYG,424270,53041,None

# Working with SQL

In [4]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in d:\anaconda\myenv\lib\site-packages (2.2.9)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import mysql.connector

In [9]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [14]:
pd.read_sql_query("select * from city where CountryCode like 'IND' ",conn)

C:\Users\Abhishek Kumar\AppData\Local\Temp\ipykernel_23372\1580018351.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from city where CountryCode like 'IND' ",conn)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [20]:
df=pd.read_sql_query("select Code,Name,Region,Population from country where LifeExpectancy > 60 ",conn)

C:\Users\Abhishek Kumar\AppData\Local\Temp\ipykernel_23372\299049368.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql_query("select Code,Name,Region,Population from country where LifeExpectancy > 60 ",conn)

In [22]:
df

    Code                  Name           Region  Population
0    ABW                 Aruba        Caribbean      103000
1    AIA              Anguilla        Caribbean        8000
2    ALB               Albania  Southern Europe     3401200
3    AND               Andorra  Southern Europe       78000
4    ANT  Netherlands Antilles        Caribbean      217000
..   ...                   ...              ...         ...
162  VIR  Virgin Islands, U.S.        Caribbean       93000
163  VNM               Vietnam   Southeast Asia    79832000
164  VUT               Vanuatu        Melanesia      190000
165  WSM                 Samoa        Polynesia      180000
166  YUG            Yugoslavia  Southern Europe    10640000

[167 rows x 4 columns]

In [27]:
dfCountrylanguage=pd.read_sql_query("select * from countrylanguage",conn)

C:\Users\Abhishek Kumar\AppData\Local\Temp\ipykernel_23372\1629443912.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dfCountrylanguage=pd.read_sql_query("select * from countrylanguage",conn)

In [28]:
dfCountrylanguage

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]